version: '3'
services:
  vrising:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9897:9897/udp"
      - "9896:9896/udp"
    # volumes:
    #   - type: bind
    #     source: ./data
    #     target: /data
    environment:
      - PERSISTENT_DATA=/data/persistent_data
      - GAME_PORT=9877
      - QUERY_PORT=9876
  # vrising-from-github:
  #   container_name: v-rising
  #   image: mephi00/v-rising-wine
  #   volumes:
  #     - type: bind
  #       source: ./saves
  #       target: /saves
  #   environment:
  #     - V_RISING_NAME=example test
  #     - V_RISING_PASSW=example password
  #     - V_RISING_SAVE_NAME=save1
  #     - V_RISING_PUBLIC_LIST=true
  #     - V_RISING_SETTING_PRESET=
  #   ports:
  #     - 9876:9876/udp
  #     - 9877:9877/udp